# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/lucas/Projects/ML-MCTS

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/lucas/Projects/ML-MCTS

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/lucas/Projects/ML-MCTS/CMakeFiles /home/lucas/Projects/ML-MCTS//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/lucas/Projects/ML-MCTS/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -P /home/lucas/Projects/ML-MCTS/CMakeFiles/VerifyGlobs.cmake
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named ML-MCTS

# Build rule for target.
ML-MCTS: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ML-MCTS
.PHONY : ML-MCTS

# fast build rule for target.
ML-MCTS/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ML-MCTS.dir/build.make CMakeFiles/ML-MCTS.dir/build
.PHONY : ML-MCTS/fast

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ML-MCTS.dir/build.make CMakeFiles/ML-MCTS.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ML-MCTS.dir/build.make CMakeFiles/ML-MCTS.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ML-MCTS.dir/build.make CMakeFiles/ML-MCTS.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/mcts.o: src/mcts.cpp.o
.PHONY : src/mcts.o

# target to build an object file
src/mcts.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ML-MCTS.dir/build.make CMakeFiles/ML-MCTS.dir/src/mcts.cpp.o
.PHONY : src/mcts.cpp.o

src/mcts.i: src/mcts.cpp.i
.PHONY : src/mcts.i

# target to preprocess a source file
src/mcts.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ML-MCTS.dir/build.make CMakeFiles/ML-MCTS.dir/src/mcts.cpp.i
.PHONY : src/mcts.cpp.i

src/mcts.s: src/mcts.cpp.s
.PHONY : src/mcts.s

# target to generate assembly for a file
src/mcts.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ML-MCTS.dir/build.make CMakeFiles/ML-MCTS.dir/src/mcts.cpp.s
.PHONY : src/mcts.cpp.s

src/neural.o: src/neural.cpp.o
.PHONY : src/neural.o

# target to build an object file
src/neural.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ML-MCTS.dir/build.make CMakeFiles/ML-MCTS.dir/src/neural.cpp.o
.PHONY : src/neural.cpp.o

src/neural.i: src/neural.cpp.i
.PHONY : src/neural.i

# target to preprocess a source file
src/neural.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ML-MCTS.dir/build.make CMakeFiles/ML-MCTS.dir/src/neural.cpp.i
.PHONY : src/neural.cpp.i

src/neural.s: src/neural.cpp.s
.PHONY : src/neural.s

# target to generate assembly for a file
src/neural.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ML-MCTS.dir/build.make CMakeFiles/ML-MCTS.dir/src/neural.cpp.s
.PHONY : src/neural.cpp.s

src/user_interface.o: src/user_interface.cpp.o
.PHONY : src/user_interface.o

# target to build an object file
src/user_interface.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ML-MCTS.dir/build.make CMakeFiles/ML-MCTS.dir/src/user_interface.cpp.o
.PHONY : src/user_interface.cpp.o

src/user_interface.i: src/user_interface.cpp.i
.PHONY : src/user_interface.i

# target to preprocess a source file
src/user_interface.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ML-MCTS.dir/build.make CMakeFiles/ML-MCTS.dir/src/user_interface.cpp.i
.PHONY : src/user_interface.cpp.i

src/user_interface.s: src/user_interface.cpp.s
.PHONY : src/user_interface.s

# target to generate assembly for a file
src/user_interface.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ML-MCTS.dir/build.make CMakeFiles/ML-MCTS.dir/src/user_interface.cpp.s
.PHONY : src/user_interface.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... ML-MCTS"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/mcts.o"
	@echo "... src/mcts.i"
	@echo "... src/mcts.s"
	@echo "... src/neural.o"
	@echo "... src/neural.i"
	@echo "... src/neural.s"
	@echo "... src/user_interface.o"
	@echo "... src/user_interface.i"
	@echo "... src/user_interface.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -P /home/lucas/Projects/ML-MCTS/CMakeFiles/VerifyGlobs.cmake
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

